const router = require('express').Router();
const authMiddleware = require('../middlewares/auth.middleware');
const githubRepo = require('../repo/github.repo');
const { Octokit } = require('@octokit/rest');

router.get('/credentials', authMiddleware, async (req, res, next) => {
  try {
    const creds = await githubRepo.findByUserId(req.user.userId);
    if (!creds) {
      return res.json({ success: true, data: null });
    }
    res.json({
      success: true,
      data: { githubUsername: creds.githubUsername, updatedAt: creds.updatedAt }
    });
  } catch (err) {
    next(err);
  }
});

router.post('/credentials', authMiddleware, async (req, res, next) => {
  try {
    const { token } = req.body;
    if (!token || typeof token !== 'string' || token.trim().length === 0) {
      return res.status(400).json({ success: false, error: 'token is required' });
    }

    const trimmedToken = token.trim();

    const octokit = new Octokit({ auth: trimmedToken });
    let ghUser;
    try {
      const { data } = await octokit.rest.users.getAuthenticated();
      ghUser = data;
    } catch {
      return res.status(401).json({
        success: false,
        error: 'Invalid GitHub token. Make sure it has the "repo" scope enabled.'
      });
    }

    await githubRepo.upsert(req.user.userId, trimmedToken, ghUser.login);

    res.json({ success: true, data: { githubUsername: ghUser.login } });
  } catch (err) {
    next(err);
  }
});

router.delete('/credentials', authMiddleware, async (req, res, next) => {
  try {
    await githubRepo.remove(req.user.userId);
    res.json({ success: true });
  } catch (err) {
    next(err);
  }
});

router.post('/push', authMiddleware, async (req, res, next) => {
  try {
    const { repoName, isPrivate, files } = req.body;

    if (!repoName || typeof repoName !== 'string' || !/^[a-zA-Z0-9_.-]+$/.test(repoName)) {
      return res.status(400).json({ success: false, error: 'repoName must be alphanumeric (hyphens, underscores, dots allowed)' });
    }
    if (typeof isPrivate !== 'boolean') {
      return res.status(400).json({ success: false, error: 'isPrivate must be a boolean' });
    }
    if (!files || typeof files !== 'object') {
      return res.status(400).json({ success: false, error: 'files object is required' });
    }

    const creds = await githubRepo.findByUserId(req.user.userId);
    if (!creds) {
      return res.status(401).json({
        success: false,
        error: 'No GitHub credentials found. Please connect your GitHub account first.'
      });
    }

    const octokit = new Octokit({ auth: creds.token });
    const owner = creds.githubUsername;

    const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      private: isPrivate,
      auto_init: true,
      description: 'Generated by Brahm'
    });

    const { data: refData } = await octokit.rest.git.getRef({
      owner,
      repo: repoName,
      ref: 'heads/main'
    });
    const latestCommitSha = refData.object.sha;

    const { data: latestCommit } = await octokit.rest.git.getCommit({
      owner,
      repo: repoName,
      commit_sha: latestCommitSha
    });
    const baseTreeSha = latestCommit.tree.sha;

    const fileEntries = Object.entries(files);
    const blobs = await Promise.all(
      fileEntries.map(([, content]) =>
        octokit.rest.git.createBlob({
          owner,
          repo: repoName,
          content: Buffer.from(content).toString('base64'),
          encoding: 'base64'
        })
      )
    );

    const tree = await octokit.rest.git.createTree({
      owner,
      repo: repoName,
      base_tree: baseTreeSha,
      tree: fileEntries.map(([path], i) => ({
        path,
        mode: '100644',
        type: 'blob',
        sha: blobs[i].data.sha
      }))
    });

    const commit = await octokit.rest.git.createCommit({
      owner,
      repo: repoName,
      message: 'Initial commit — generated by Brahm',
      tree: tree.data.sha,
      parents: [latestCommitSha]
    });

    await octokit.rest.git.updateRef({
      owner,
      repo: repoName,
      ref: 'heads/main',
      sha: commit.data.sha
    });

    res.json({ success: true, data: { repoUrl: repo.html_url } });
  } catch (err) {
    if (err.status === 422) {
      const friendlyError = new Error('A repository with that name already exists on your GitHub account.');
      friendlyError.status = 422;
      return next(friendlyError);
    }
    if (err.status === 401) {
      const friendlyError = new Error('GitHub token is no longer valid. Please reconnect your GitHub account.');
      friendlyError.status = 401;
      return next(friendlyError);
    }
    next(err);
  }
});

module.exports = router;
